/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-01-19 15:48:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.NEWPROJECT.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Camnangdulich_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/NEWPROJECT/html/footer.jsp", Long.valueOf(1453172742654L));
    _jspx_dependants.put("/NEWPROJECT/html/seach.jsp", Long.valueOf(1453172742717L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"><!-- InstanceBegin template=\"/Templates/Camnangdulich.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>CẨM NANG DU LỊCH</title>\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/camnang.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/GioiThieuCamNang.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/NEWPROJECT/NEWPROJECT/css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/UpdateAddmin/stylenewaddmin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>CẨM NANG DU LỊCH</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/NEWPROJECT/NEWPROJECT/css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/UpdateAddmin/stylenewaddmin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Start WOWSlider.com HEAD section -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/NEWPROJECT/NEWPROJECT/engine1/style.css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/index/body_contenner.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/NEWPROJECT/NEWPROJECT/engine1/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- End WOWSlider.com HEAD section -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write(" <div id=\"right\">\r\n");
      out.write("    <div id=\"video\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-sm-5\">\r\n");
      out.write("            <h3>\r\n");
      out.write("              <p >Du Lịch Việt</p>\r\n");
      out.write("            </h3>\r\n");
      out.write("            <div class=\"embed-responsive embed-responsive-16by9\">\r\n");
      out.write("              <iframe class=\"embed-responsive-item\" src=\"../video/Welcome to vietnam.mp4\"></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p ><strong>Đến với Việt Nam để cảm nhận những vẻ đẹp tiềm ẩn.\r\n");
      out.write("              Cùng với màu sắc văn hóa rực rỡ của 54 dân tộc. </strong></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--start seach-->\r\n");
      out.write("    <div id=\"seach\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        <p style=\"color:#F00;\">Tìm Tour Du Lịch</p>\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\">Khởi Hành Từ</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseOne\" class=\"panel-collapse collapse in\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=1\">\r\n");
      out.write("                  <input type=\"checkbox\" checked=\"checked\" />\r\n");
      out.write("                  Hồ Chí Minh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=3\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Hà Nội</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=4\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Đà Nẵng</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=5\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Cần Thơ</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=6\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Hải Phòng</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=8\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Nha Trang</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=10\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Huế</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=11\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quy Nhơn</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=15\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quảng Ngãi</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=17\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quảng Ninh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=18\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Buôn Ma Thuột</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=19\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Vinh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=20\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Cà Mau</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=22\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Rạch Giá</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\">Theo Giá</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseTwo\" class=\"panel-collapse collapse\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul >\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=0\">\r\n");
      out.write("                  <input type=\"checkbox\" checked=\"checked\" />\r\n");
      out.write("                  Tất cả</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=25\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Dưới 1 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=26\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  1- 2  Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=27\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  2-4 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=28\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  4-6 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=29\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  6-10 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=30\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Trên 10 Triệu</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\">Theo Miền</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseThree\" class=\"panel-collapse collapse\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-bac.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền bắc</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-trung.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền trung</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-tay.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền tây</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-dong.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền đông</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <h3><a href=\"#\" class=\"btn btn-primary btn-block\" role=\"button\">Tìm Kiếm</a></h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--end seachs-->\r\n");
      out.write("    <!--start Khuyen Mai-->\r\n");
      out.write("    <div id=\"khuyen_mai\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        <p style=\"color:#F00;\">Tour Bán Chạy Nhất</p>\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div id=\"row\">\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--end Khuyen Mai-->\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <div class=\"tittle\">\r\n");
      out.write("    <div class=\"backgr\">Du Lịch Việt Nam</div>\r\n");
      out.write("  </div>\r\n");
      out.write(" \t<div class=\"list\">\r\n");
      out.write("    <div class=\"wap_location_right\">\r\n");
      out.write("    \t<ul class=\"filter\">\r\n");
      out.write("               <li><a class=\"image\" href=\"DuLichDaLat.jsp\"><img title=\"Đà Lạt tháng 7 - Ai đem mưa phùn qua phố?\" alt=\"Đà Lạt tháng 7 - Ai đem mưa phùn qua phố?\" src=\"../img/Camnangdulich/medium_ejz1446353394.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Đà Lạt tháng 7 - Ai đem mưa phùn qua phố?\" href=\"DuLichDaLat.jsp\">Đà Lạt tháng 7 - Ai đem mưa phùn qua phố?</a></h2>\r\n");
      out.write("           <div class=\"detail\">Đà Lạt tháng 7 tựa những ngày mộng tưởng cho những ai lạc bước giữa chốn thanh sơ. Tháng 7 của Đà Lạt là tháng của những ngày không nắng, của gót chân người lữ khách tìm về phố mơ. Mytour muốn khẽ nâng đôi chân bạn trong một làn sương biếc, gởi bạn đến nơi của những thi ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"DuLichDaLat.jsp\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("            <a class=\"image\" href=\"DuLichConDao.jsp\"><img title=\"Côn Đảo - Có gì nơi thiên đường của sóng\" alt=\"Côn Đảo - Có gì nơi thiên đường của sóng\" src=\"../img/Camnangdulich/medium_bru1446352638.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Côn Đảo - Có gì nơi thiên đường của sóng\" href=\"DuLichConDao.jsp\">Côn Đảo - Có gì nơi thiên đường của sóng</a></h2>\r\n");
      out.write("               <div class=\"detail\"> Có những lúc thèm cảm giác được chạy chân trần trên nền cát mịn, được vẫy vùng trong làn nước trong xanh của đại dương và mở căng lồng ngực hít hà hương biển cả. Rồi bước chân lại vội vã tìm về Côn Đảo để thỏa nỗi nhớ mong, để được hòa mình cùng làn gió mát lành chốn ... </div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"DuLichConDao.jsp\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("\r\n");
      out.write("                  <li>\r\n");
      out.write("            <a class=\"image\" href=\"DuLichSapa.jsp\"><img title=\"Ngất ngây đất trời Sapa tháng 4 đượm hương sắc hoa rừng\" alt=\"Ngất ngây đất trời Sapa tháng 4 đượm hương sắc hoa rừng\" src=\"../img/Camnangdulich/medium_qum1446285595.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Ngất ngây đất trời Sapa tháng 4 đượm hương sắc hoa rừng\" href=\"DuLichSapa.jsp\">Ngất ngây đất trời Sapa tháng 4 đượm hương sắc hoa rừng</a></h2>\r\n");
      out.write("             <div class=\"detail\">Sapa đẹp ngây ngất, mùa nào Sapa cũng quyến rũ đến say lòng người. Ấy thế mà có những gã viễn khách đem lòng mình dâng Sapa một ngày tháng 4 đã không níu về được mà để mãi chốn đây. Sapa tháng 4 là bát rượu, tiếng sáo làm biết bao người mê mẩn. Mytour cũng muốn thổi một ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"DuLichSapa.jsp\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Sapa tháng 10 tan trong dư âm hương lúa\" alt=\"Sapa tháng 10 tan trong dư âm hương lúa\" src=\"../img/Camnangdulich/medium_pxl1446283219.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Sapa tháng 10 tan trong dư âm hương lúa\" href=\"\">Sapa tháng 10 tan trong dư âm hương lúa</a></h2>\r\n");
      out.write("            <div class=\"detail\">Tháng 10 Sapa tan trong lúa. Ấy vẫn là những thơ tình dịu dàng nhưng có phần hoang … âm hưởng núi đồi. Những ruộng bậc thang mênh mang chìm trong lúa vàng như sóng, lúa gặt về đụn lên những đám rơm vàng thơm tho. Người đến Sapa tưởng chừng như bị mảnh đất ấy cuốn ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("         \r\n");
      out.write("           <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Mộc Châu tháng 1 khi xuân tràn mọi nẻo\" alt=\"Mộc Châu tháng 1 khi xuân tràn mọi nẻo\" src=\"../img/Camnangdulich/medium_pop1446262131.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Mộc Châu tháng 1 khi xuân tràn mọi nẻo\" href=\"\">Mộc Châu tháng 1 khi xuân tràn mọi nẻo</a></h2>\r\n");
      out.write("           <div class=\"detail\">Mộc Châu là cao nguyên rộng lớn và xinh đẹp nhất miền núi phía bắc, có khí hậu ôn đới gió mùa, quanh năm mát mẻ. Một ngày nào đó, khi đôi chân bạn lạc đến Mộc Châu vào tháng 1, bạn sẽ dành cho nơi đây một tình yêu thiên nhiên và con người vô bờ bến, bạn sẽ rung động cả ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("          \r\n");
      out.write("              <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Mộc Châu có gì khi tháng 3 chạm ngõ?\" alt=\"Mộc Châu có gì khi tháng 3 chạm ngõ?\" src=\"../img/Camnangdulich/medium_mad1446114596.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Mộc Châu có gì khi tháng 3 chạm ngõ?\" href=\"\">Mộc Châu có gì khi tháng 3 chạm ngõ?</a></h2>\r\n");
      out.write(" <div class=\"detail\">Khi những ngày xuân âm lịch đã qua, khi hoa đào, hoa mận đã thôi không còn rực rỡ, Mộc Châu tháng 3 lại miên man trong sắc hoa ban dịu dàng, ngây ngất. Nhiều người thích mùa cải trắng tinh như tuyết phủ khắp cánh đồng, mong chờ xuân để lên Tây Bắc săn ảnh đào tươi thắm ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               <p></p>\r\n");
      out.write("          </li>   \r\n");
      out.write("             <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Mộc Châu tháng 4 - Ngất ngây trong sắc xanh của núi rừng\" alt=\"Mộc Châu tháng 4 - Ngất ngây trong sắc xanh của núi rừng\" src=\"../img/Camnangdulich/medium_zyp1446284939.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Mộc Châu tháng 4 - Ngất ngây trong sắc xanh của núi rừng\" href=\"\">Mộc Châu tháng 4 - Ngất ngây trong sắc xanh của núi rừng</a></h2>\r\n");
      out.write("   <div class=\"detail\">Tôi yêu Mộc Châu những ngày đông bạt ngàn sắc trắng tinh khôi của cải, yêu những ngày xuân nồng nàn trong sắc mận sắc đào và tôi cũng yêu Mộc Châu tháng 4 về ngập tràn trong màu xanh mướt của núi đồi, bình lặng đưa lòng người vào những cõi an yên. Mộc Châu tháng 4 như ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Tiết đông Đà Lạt tháng 12 có gì lưu luyến?\" alt=\"Tiết đông Đà Lạt tháng 12 có gì lưu luyến?\" src=\"../img/Camnangdulich/medium_hfa1446265498.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Tiết đông Đà Lạt tháng 12 có gì lưu luyến?\" href=\"\">Tiết đông Đà Lạt tháng 12 có gì lưu luyến?</a></h2>\r\n");
      out.write("           <div class=\"detail\">Nếu để gọi tên mùa nào đẹp nhất, khiến trái tim người phương xa muốn xê dịch để ôm lấy thành phố cao nguyên Đà Lạt nhất, có lẽ không ít người sẽ lựa chọn mùa đông. Đông đến với Đà Lạt một cách rất nhẹ nhàng như có lời hẹn ước, khi màn mưa cuối cùng cũng chịu ngưng và ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Có gì chơi ở Củ Chi trong những ngày nắng đẹp?\" alt=\"Có gì chơi ở Củ Chi trong những ngày nắng đẹp?\" src=\"../img/Camnangdulich/medium_ydc1446214794.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Có gì chơi ở Củ Chi trong những ngày nắng đẹp?\" href=\"\">Có gì chơi ở Củ Chi trong những ngày nắng đẹp?</a></h2>\r\n");
      out.write("             <div class=\"detail\">Cách trung tâm thành phố Hồ Chí Minh chỉ khoảng 70 km về phía Tây Bắc, Củ Chi là điểm đến lý tưởng trong ngày cho những ai đã chán cảnh ồn ào xô bồ ở thành thị, muốn hòa mình cao thiên nhiên, tìm hiểu cuộc sống của người dân miền “đất thép thành đồng” lừng ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Mộc Châu mộc mạc mùa chè xanh tháng 5\" alt=\"Mộc Châu mộc mạc mùa chè xanh tháng 5\" src=\"../img/Camnangdulich/medium_uvi1446201500.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Mộc Châu mộc mạc mùa chè xanh tháng 5\" href=\"\">Mộc Châu mộc mạc mùa chè xanh tháng 5</a></h2>\r\n");
      out.write("  <div class=\"detail\">Mộc Châu tháng 5 một mùa hoa mới lại về, cả đất trời tựa như một thiên đường tuyết trắng muốt ngập tràn sắc hoa mận. Nói Mộc Châu là mảnh đất của những mùa hoa quả thật không ngoa. Nếu xuân đến là mùa hoa đào cùng những bụi dã quỳ đan xen nhau rực rỡ cả một triền đồi ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("        \r\n");
      out.write("                  <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Cuối tuần lên Tam Đảo có gì chơi?\" alt=\"Cuối tuần lên Tam Đảo có gì chơi?\" src=\"../img/Camnangdulich/medium_nff1446213768.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Cuối tuần lên Tam Đảo có gì chơi?\" href=\"\">Cuối tuần lên Tam Đảo có gì chơi?</a></h2>\r\n");
      out.write(" <div class=\"detail\">Tam Đảo ngay gần Hà Nội. Cuối tuần phi xe máy hay nhảy xe ô tô thì cũng chỉ độ 2 tiếng là tới nơi. Có lẽ vì thế mà người tới Tam Đảo nhiều, quanh năm nơi đây luôn có khách du lịch. Nhưng Tam Đảo kể ra cũng nhỏ lắm, đi dạo một hồi là hết cả cái thị trấn bé con ấy rồi. ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("               \r\n");
      out.write("                  <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Đà Lạt tháng 5 những ngày mưa mộng mị?\" alt=\"Đà Lạt tháng 5 những ngày mưa mộng mị?\" src=\"../img/Camnangdulich/medium_xil1446259410.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Đà Lạt tháng 5 những ngày mưa mộng mị?\" href=\"\">Đà Lạt tháng 5 những ngày mưa mộng mị?</a></h2>\r\n");
      out.write("      <div class=\"detail\">Đà Lạt mùa nào cũng xinh đẹp như một nàng thơ. Tháng 5 yêu kiều để lại cho Đà Lạt những ngày mê say và có phần đỏng đảnh. Tháng 5, tháng bắt đầu của những ngày mưa, nàng công chúa miên man những nỗi niềm Đà Lạt khiến lòng người có chút xuyến xao.\r\n");
      out.write("&nbsp;\r\n");
      out.write("\r\n");
      out.write("Đà Lạt tháng ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Có gì chờ đợi ta ở Sapa tháng 12?\" alt=\"Có gì chờ đợi ta ở Sapa tháng 12?\" src=\"../img/Camnangdulich/medium_gkq1446256462.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Có gì chờ đợi ta ở Sapa tháng 12?\" href=\"\">Có gì chờ đợi ta ở Sapa tháng 12?</a></h2>\r\n");
      out.write("           <div class=\"detail\">Nằm ở phía Tây Bắc của Tổ quốc, SaPa là một huyện vùng cao của tỉnh Lào Cai, một vùng đất ẩn chứa bao điều kì diệu của cảnh sắc thiên nhiên và con người. Vào những ngày đầu tháng 12, khi những cơn gió mùa đông bắc thổi về ngang qua những cung đường của vùng đất rẻo cao ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            <a class=\"image\" href=\"\"><img title=\"Cam Ranh có gì chơi trong những ngày nắng gọi?\" alt=\"Cam Ranh có gì chơi trong những ngày nắng gọi?\" src=\"../img/Camnangdulich/medium_tgy1446212990.jpg\" /></a>\r\n");
      out.write("            <h2><a title=\"Cam Ranh có gì chơi trong những ngày nắng gọi?\" href=\"\">Cam Ranh có gì chơi trong những ngày nắng gọi?</a></h2>\r\n");
      out.write("   <div class=\"detail\">Từ vài năm trở lại đây, Cam Ranh là thiên đường cho những ai yêu tiếng sóng biển, yêu màu xanh của nền trời. Mytour sẽ mang bạn đến chốn đây và trả lời cho bạn câu hỏi Cam Ranh có gì chơi? Phải chăng nơi đây là nhà của gió, của biển, của những hòn đảo thanh bình đến mê ...</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("        \r\n");
      out.write("\t</ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"page_breakbar\">\r\n");
      out.write("    <ul class=\"pagination\">\r\n");
      out.write("  <li><a href=\"#\">&laquo;</a></li>\r\n");
      out.write("  <li><a href=\"#\">1</a></li>\r\n");
      out.write("  <li><a href=\"#\">2</a></li>\r\n");
      out.write("  <li><a href=\"#\">3</a></li>\r\n");
      out.write("  <li><a href=\"#\">&raquo;</a></li></ul>\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  </div></div>\r\n");
      out.write("  \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/NEWPROJECT/NEWPROJECT/css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <footer class=\"footer-distributed\">\r\n");
      out.write("    <div class=\"footer-left\">\r\n");
      out.write("      <h3>Du Lịch V<span>à Cuộc Sống</span></h3>\r\n");
      out.write("      <p class=\"footer-links\"> <a href=\"home.jsp\">Trang Chủ</a> ·\r\n");
      out.write("       <a href=\"Camnangdulich.jsp\">Cẩm nang</a> · <a href=\"DuLichTrongNuoc.jsp\">Du Lịch Nội Địa</a> \r\n");
      out.write("       · <a href=\"DuLichNuocNgoai.jsp\">Du Lịch Nước Ngoài</a> \r\n");
      out.write("       · <a href=\"#\">Khách Hàng</a> · <a href=\"GioiThieu.jsp\">Giới Thiệu</a></p>\r\n");
      out.write("      <p class=\"footer-company-name\">CÔNG TY DU LỊCH VIỆT 2015</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-center\">\r\n");
      out.write("      <div> <i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("        <p><span> 175, Nguyễn Thái Bình ,</span>Quận 1,Tp.HCM.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("        <p>+1 555 123456</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("        <p><a href=\"mailto:support@company.com\">phongkhachhang@vtc.com</a></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-right\">\r\n");
      out.write("      <p class=\"footer-company-about\"> <span>Công ty Du lịch Việt</span> Tận hưởng chuyến du lịch đầy ý nghĩa.</p>\r\n");
      out.write("      <div class=\"footer-icons\"> <a href=\"#\"><i class=\"fa fa-facebook\"></i></a> <a href=\"#\"><i class=\"fa fa-twitter\"></i></a> <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a> <a href=\"#\"><i class=\"fa fa-github\"></i></a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <!-- InstanceEndEditable --></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- InstanceEnd --></html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
