/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-01-21 02:58:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.NEWPROJECT.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.IMG;
import Model.HandBook;
import java.util.ArrayList;

public final class Camnangdulich_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/NEWPROJECT/html/footer.jsp", Long.valueOf(1453172742654L));
    _jspx_dependants.put("/NEWPROJECT/html/seach.jsp", Long.valueOf(1453172742717L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"><!-- InstanceBegin template=\"/Templates/Camnangdulich.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>CẨM NANG DU LỊCH</title>\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/camnang.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/GioiThieuCamNang.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/NEWPROJECT/NEWPROJECT/css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/UpdateAddmin/stylenewaddmin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#header').load(\"LoadDataHeader\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
 ArrayList<HandBook> listHandBook = (ArrayList<HandBook>)session.getAttribute("listAllHandBook"); 
      out.write("\r\n");
      out.write("<div id=\"header\"></div>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>CẨM NANG DU LỊCH</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/NEWPROJECT/NEWPROJECT/css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/UpdateAddmin/stylenewaddmin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Start WOWSlider.com HEAD section -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/NEWPROJECT/NEWPROJECT/engine1/style.css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/index/body_contenner.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/NEWPROJECT/NEWPROJECT/engine1/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- End WOWSlider.com HEAD section -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write(" <div id=\"right\">\r\n");
      out.write("    <div id=\"video\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-sm-5\">\r\n");
      out.write("            <h3>\r\n");
      out.write("              <p >Du Lịch Việt</p>\r\n");
      out.write("            </h3>\r\n");
      out.write("            <div class=\"embed-responsive embed-responsive-16by9\">\r\n");
      out.write("              <iframe class=\"embed-responsive-item\" src=\"../video/Welcome to vietnam.mp4\"></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p ><strong>Đến với Việt Nam để cảm nhận những vẻ đẹp tiềm ẩn.\r\n");
      out.write("              Cùng với màu sắc văn hóa rực rỡ của 54 dân tộc. </strong></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--start seach-->\r\n");
      out.write("    <div id=\"seach\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        <p style=\"color:#F00;\">Tìm Tour Du Lịch</p>\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\">Khởi Hành Từ</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseOne\" class=\"panel-collapse collapse in\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=1\">\r\n");
      out.write("                  <input type=\"checkbox\" checked=\"checked\" />\r\n");
      out.write("                  Hồ Chí Minh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=3\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Hà Nội</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=4\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Đà Nẵng</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=5\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Cần Thơ</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=6\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Hải Phòng</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=8\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Nha Trang</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=10\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Huế</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=11\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quy Nhơn</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=15\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quảng Ngãi</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=17\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quảng Ninh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=18\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Buôn Ma Thuột</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=19\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Vinh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=20\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Cà Mau</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=22\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Rạch Giá</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\">Theo Giá</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseTwo\" class=\"panel-collapse collapse\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul >\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=0\">\r\n");
      out.write("                  <input type=\"checkbox\" checked=\"checked\" />\r\n");
      out.write("                  Tất cả</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=25\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Dưới 1 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=26\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  1- 2  Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=27\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  2-4 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=28\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  4-6 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=29\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  6-10 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=30\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Trên 10 Triệu</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\">Theo Miền</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseThree\" class=\"panel-collapse collapse\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-bac.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền bắc</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-trung.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền trung</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-tay.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền tây</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-dong.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền đông</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <h3><a href=\"#\" class=\"btn btn-primary btn-block\" role=\"button\">Tìm Kiếm</a></h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--end seachs-->\r\n");
      out.write("    <!--start Khuyen Mai-->\r\n");
      out.write("    <div id=\"khuyen_mai\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        <p style=\"color:#F00;\">Tour Bán Chạy Nhất</p>\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div id=\"row\">\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--end Khuyen Mai-->\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <div class=\"tittle\">\r\n");
      out.write("    <div class=\"backgr\">Du Lịch Việt Nam</div>\r\n");
      out.write("  </div>\r\n");
      out.write(" \t<div class=\"list\">\r\n");
      out.write("    <div class=\"wap_location_right\">\r\n");
      out.write("    \t<ul class=\"filter\">\r\n");
      out.write("    \t");
for (HandBook list : listHandBook){
    		list.getIdHandBook();
    	
      out.write("\r\n");
      out.write("    \t<li><a class=\"image\" href=\"");
      out.print( list.getIdHandBook());
      out.write("\">\r\n");
      out.write("    \t<img title=\"");
      out.print( list.getTitle() );
      out.write("\" src=\"Resource?url=");
      out.print(list.getMainImg());
      out.write("\" /></a>\r\n");
      out.write("            <h2><a href=\"DuLichDaLat.jsp\">");
      out.print( list.getTitle() );
      out.write("</a></h2>\r\n");
      out.write("           <div class=\"detail\">");
      out.print( list.getShortContent() );
      out.write("</div>\r\n");
      out.write("               <p class=\"view_more\"><a href=\"DuLichDaLat.jsp\">Xem thêm</a></p>\r\n");
      out.write("               \r\n");
      out.write("         </li>\r\n");
      out.write("    \t");
 } 
      out.write("\r\n");
      out.write("          \r\n");
      out.write("\t</ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"page_breakbar\">\r\n");
      out.write("    <ul class=\"pagination\">\r\n");
      out.write("  <li><a href=\"#\">&laquo;</a></li>\r\n");
      out.write("  <li><a href=\"#\">1</a></li>\r\n");
      out.write("  <li><a href=\"#\">2</a></li>\r\n");
      out.write("  <li><a href=\"#\">3</a></li>\r\n");
      out.write("  <li><a href=\"#\">&raquo;</a></li></ul>\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  </div></div>\r\n");
      out.write("  \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/NEWPROJECT/NEWPROJECT/css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <footer class=\"footer-distributed\">\r\n");
      out.write("    <div class=\"footer-left\">\r\n");
      out.write("      <h3>Du Lịch V<span>à Cuộc Sống</span></h3>\r\n");
      out.write("      <p class=\"footer-links\"> <a href=\"home.jsp\">Trang Chủ</a> ·\r\n");
      out.write("       <a href=\"Camnangdulich.jsp\">Cẩm nang</a> · <a href=\"DuLichTrongNuoc.jsp\">Du Lịch Nội Địa</a> \r\n");
      out.write("       · <a href=\"DuLichNuocNgoai.jsp\">Du Lịch Nước Ngoài</a> \r\n");
      out.write("       · <a href=\"#\">Khách Hàng</a> · <a href=\"GioiThieu.jsp\">Giới Thiệu</a></p>\r\n");
      out.write("      <p class=\"footer-company-name\">CÔNG TY DU LỊCH VIỆT 2015</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-center\">\r\n");
      out.write("      <div> <i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("        <p><span> 175, Nguyễn Thái Bình ,</span>Quận 1,Tp.HCM.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("        <p>+1 555 123456</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("        <p><a href=\"mailto:support@company.com\">phongkhachhang@vtc.com</a></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-right\">\r\n");
      out.write("      <p class=\"footer-company-about\"> <span>Công ty Du lịch Việt</span> Tận hưởng chuyến du lịch đầy ý nghĩa.</p>\r\n");
      out.write("      <div class=\"footer-icons\"> <a href=\"#\"><i class=\"fa fa-facebook\"></i></a> <a href=\"#\"><i class=\"fa fa-twitter\"></i></a> <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a> <a href=\"#\"><i class=\"fa fa-github\"></i></a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <!-- InstanceEndEditable --></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- InstanceEnd --></html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
