/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-01-06 16:38:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.NEWPROJECT.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Controller.LoadData;
import java.util.ArrayList;
import org.apache.jasper.tagplugins.jstl.core.ForEach;
import DAO.TypeTourDaoImp;
import Model.Tour_Type;

public final class GioiThieu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/NEWPROJECT/html/header.jsp", Long.valueOf(1452055796125L));
    _jspx_dependants.put("/NEWPROJECT/html/footer.jsp", Long.valueOf(1451809395344L));
    _jspx_dependants.put("/NEWPROJECT/html/seach.jsp", Long.valueOf(1451809395544L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"><!-- InstanceBegin template=\"/Templates/home.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>Giới Thiệu Công Ty</title>\r\n");
      out.write("<link href=\"../css/GioiThieuCamNang.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"../Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"../Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../css/UpdateAddmin/stylenewaddmin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"../css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<!-- InstanceBegin template=\"/Templates/home.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"../Bootstrap/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../Bootstrap/glyphicons.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/bootstrap/js/bootstrap.min.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"../css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Start WOWSlider.com HEAD section -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../engine1/style.css\" />\r\n");
      out.write("<link href=\"../SpryAssets/SpryAccordion.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../engine1/jquery.js\"></script>\r\n");
      out.write("<!-- End WOWSlider.com HEAD section -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		ArrayList<Tour_Type> listTypeTour = (ArrayList<Tour_Type>) session.getAttribute("listTypeTour");
	
      out.write("\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<div id=\"login_loout\">\r\n");
      out.write("\t\t\t\t<div id=\"DangKy\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Đăng Ký </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"DangNhap\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"> Đăng Nhập </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"LienHe\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"> Liên Hệ </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"banner\">\r\n");
      out.write("\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../img/logo/flower banner 1 - Copy.jpg\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Nhập tour cần tìm...\" s /> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-default\" type=\"button\">Seach</button>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /input-group -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.col-lg-6 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"header-hot-line\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-phone-square fa-2x \"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: left; padding-right: 2px;\"></i> <span>\r\n");
      out.write("\t\t\t\t\t\t\t(04-3) 511.33.33<em style=\"color: #666 !important;\">-</em>\r\n");
      out.write("\t\t\t\t\t\t\t01999.102.888\r\n");
      out.write("\t\t\t\t\t\t</span> <i id=\"txt\">(Thời gian làm việc: 8:00 - 17:30 các ngày trong\r\n");
      out.write("\t\t\t\t\t\t\ttuần)</i>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div></div>\r\n");
      out.write("\t\t\t<!--end header-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- InstanceBeginEditable name=\"Change\" -->\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"home.jsp\"><i class=\"fa fa-home\"></i>Trang\r\n");
      out.write("\t\t\t\t\t\t\t\tchủ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"Camnangdulich.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-book\"></i>Cẩm Nan Du Lịch</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Du Lịch Trong Nước<span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"caret\"></span></a> </a> ");

 	for (Tour_Type los : listTypeTour) {
 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> ");
      out.print(los.getNameType() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Menu 1 <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Submenu 1-1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Submenu 1-2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Submenu 1-3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"file:///G|/NEWPROJECT/dangNhap.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-users\"></i>Khách Hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"GioiThieu.jsp\"><i class=\"fa fa-user\"></i>Giới\r\n");
      out.write("\t\t\t\t\t\t\t\tThiệu</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- InstanceEndEditable -->\r\n");
      out.write("\t\t<!-- InstanceBeginEditable name=\"change\" -->\r\n");
      out.write("\t\t<div id=\"slider\">\r\n");
      out.write("\t\t\t<!-- Start WOWSlider.com BODY section -->\r\n");
      out.write("\t\t\t<div id=\"wowslider-container1\">\r\n");
      out.write("\t\t\t\t<div class=\"ws_images\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><img src=\"../data1/images/01.jpg\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"wows1_0\" /></li>\r\n");
      out.write("\t\t\t\t\t\t<li><img src=\"../data1/images/02.jpg\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"wows1_1\" /></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://wowslider.net\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/images/03.jpg\" alt=\"wowslider.net\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"wows1_2\" /></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><img src=\"../data1/images/04.jpg\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"wows1_3\" /></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ws_bullets\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" title=\"\"><span><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/images/01.jpg\" alt=\"\" />1</span></a> <a href=\"#\" title=\"\"><span><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/tooltips/02.jpg\" alt=\"\" />2</span></a> <a href=\"#\" title=\"\"><span><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/tooltips/03.jpg\" alt=\"\" />3</span></a> <a href=\"#\" title=\"\"><span><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/tooltips/04.jpg\" alt=\"\" />4</span></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ws_script\" style=\"position: absolute; left: -99%\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://wowslider.com\">bootstrap carousel</a> by\r\n");
      out.write("\t\t\t\t\tWOWSlider.com v8.6\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ws_shadow\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"../engine1/wowslider.js\"></script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"../engine1/script.js\"></script>\r\n");
      out.write("\t\t\t<!-- End WOWSlider.com BODY section -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End Content Wrapper. Contains page content -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>CẨM NANG DU LỊCH</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"../Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"../Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../css/UpdateAddmin/stylenewaddmin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"../css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Start WOWSlider.com HEAD section -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../engine1/style.css\" />\r\n");
      out.write("<link href=\"../css/index/body_contenner.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../SpryAssets/SpryAccordion.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../engine1/jquery.js\"></script>\r\n");
      out.write("<script src=\"../SpryAssets/SpryAccordion.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- End WOWSlider.com HEAD section -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write(" <div id=\"right\">\r\n");
      out.write("    <div id=\"video\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-sm-5\">\r\n");
      out.write("            <h3>\r\n");
      out.write("              <p >Du Lịch Việt</p>\r\n");
      out.write("            </h3>\r\n");
      out.write("            <div class=\"embed-responsive embed-responsive-16by9\">\r\n");
      out.write("              <iframe class=\"embed-responsive-item\" src=\"../video/Welcome to vietnam.mp4\"></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p ><strong>Đến với Việt Nam để cảm nhận những vẻ đẹp tiềm ẩn.\r\n");
      out.write("              Cùng với màu sắc văn hóa rực rỡ của 54 dân tộc. </strong></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--start seach-->\r\n");
      out.write("    <div id=\"seach\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        <p style=\"color:#F00;\">Tìm Tour Du Lịch</p>\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\">Khởi Hành Từ</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseOne\" class=\"panel-collapse collapse in\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=1\">\r\n");
      out.write("                  <input type=\"checkbox\" checked=\"checked\" />\r\n");
      out.write("                  Hồ Chí Minh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=3\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Hà Nội</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=4\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Đà Nẵng</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=5\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Cần Thơ</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=6\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Hải Phòng</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=8\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Nha Trang</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=10\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Huế</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=11\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quy Nhơn</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=15\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quảng Ngãi</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=17\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quảng Ninh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=18\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Buôn Ma Thuột</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=19\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Vinh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=20\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Cà Mau</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=22\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Rạch Giá</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\">Theo Giá</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseTwo\" class=\"panel-collapse collapse\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul >\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=0\">\r\n");
      out.write("                  <input type=\"checkbox\" checked=\"checked\" />\r\n");
      out.write("                  Tất cả</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=25\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Dưới 1 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=26\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  1- 2  Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=27\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  2-4 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=28\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  4-6 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=29\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  6-10 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=30\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Trên 10 Triệu</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\">Theo Miền</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseThree\" class=\"panel-collapse collapse\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-bac.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền bắc</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-trung.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền trung</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-tay.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền tây</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-dong.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền đông</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <h3><a href=\"#\" class=\"btn btn-primary btn-block\" role=\"button\">Tìm Kiếm</a></h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--end seachs-->\r\n");
      out.write("    <!--start Khuyen Mai-->\r\n");
      out.write("    <div id=\"khuyen_mai\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        <p style=\"color:#F00;\">Tour Bán Chạy Nhất</p>\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div id=\"row\">\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--end Khuyen Mai-->\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <div class=\"tittle\">\r\n");
      out.write("    <div class=\"backgr\">Công ty Du Lịch Việt</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"list\">\r\n");
      out.write("  \t<div class=\"row\">\r\n");
      out.write("     <h1 style=\"font-size: 22px;color:#0371B1;margin-top:5px;margin-bottom:15px;margin-left:20px;\">I. Giới thiệu</h1>\r\n");
      out.write("      <p>Công ty Cổ phần dịch vụ thương mại Du Lịch Việt có tên thương hiệu là công ty Du Lịch Việt, tên giao dịch là Viet Travel Joint Stock Trade Services Company(VTC).</p>\r\n");
      out.write("<p>Trụ sở chính đặt tại 175, Nguyễn Thái Bình, Quận 1, Tp.HCM.</p>\r\n");
      out.write("<p>Du lịch ngày nay đã trở thành nhu cầu của mỗi chúng ta. Là một trong những đơn vị hoạt động kinh doanh trong lĩnh vực truyền thông và du lịch tại Việt Nam,</p>\r\n");
      out.write("<p> từ khi thành lập đến nay, công ty Du Lịch Việt đã có những bước tiến vượt bậc. Với đội ngũ nhân viên giỏi, nhiệt tình, đam mê nghề nghiệp được đào tạo trong và ngoài nước,</p>\r\n");
      out.write("<p> những hướng dẫn viên nhiều năm kinh nghiệm trong lĩnh vực du lịch, phục vụ du lịch, đã có đóng góp không nhỏ cho ngành du lịch Việt Nam.</p>\r\n");
      out.write("<p>Bên cạnh các sản phẩm dịch vụ visa, đặt vé máy bay, dịch vụ cho thuê xe du lịch, dịch vụ nhà hàng, khách sạn, hoạt động kinh doanh chính của công ty là thiết kế và </p>\r\n");
      out.write("<p>thực hiện một cách chuyên nghiệp các tour du lịch tham quan, tour hành hương, nghỉ dưỡng kết hợp thăm thân nhân trong và ngoài nước.</p>\r\n");
      out.write("<p>Công ty Du Lịch Việt đã chính thức đặt văn phòng đại diện tại Hoa Kỳ, và tổ chức được đội ngũ hướng dẫn viên là Việt Kiều có hiểu biết cặn kẽ về văn hóa Việt Nam </p>\r\n");
      out.write("<p>cũng như các nền văn hóa bản địa.</p>\r\n");
      out.write("<div class=\"a_img\">\r\n");
      out.write(" <img src=\"../img/GioiThieu/giay-phep-kinh-doanh-lu-hoanh-quoc-te-mat-truoc.jpg\" alt=\"mat truoc giay phep kinh doanh lu hoanh quoc te\" width=\"400\" height=\"450\" style=\"margin-left:100px;margin-right:100px\">\r\n");
      out.write(" <p>Mặt trước giấy phép kinh doanh lữ hoành quốc tế</p>\r\n");
      out.write("<img src=\"../img/GioiThieu/giay-phep-kinh-doanh-lu-hoanh-quoc-te-mat-sau.jpg\" alt=\"mat sau giay phep kinh doanh lu hoanh quoc te\" width=\"400\" height=\"450\" style=\"margin-left:100px;margin-right:100px\">\r\n");
      out.write("<p>Mặt sau giấy phép kinh doanh lữ hoành quốc tế</p></div>\r\n");
      out.write("<p>Bên cạnh hoạt động kinh doanh, công ty Du Lịch Việt còn thường xuyên tham gia tài trợ cho chương trình nhân đạo, các hoạt động vì cộng đồng như :</p>\r\n");
      out.write("<p>chương trình hiến máu nhân đạo, chương trình cứu giúp nạn nhân bão lụt, tài trợ giải thưởng cho game show “Hãy chọn giá đúng”…</p>\r\n");
      out.write("<p>Mục tiêu phát triển tiếp theo của công ty là tập trung đẩy mạnh kinh doanh trực tuyến: dịch vụ đặt tour &amp; thanh toán tour trực tuyến, dịch vụ đặt khách sạn,</p>\r\n");
      out.write("<p> đặt xe trực tuyến. Chấp nhận thanh toán đa dạng các loại thẻ như thẻ nội địa, thẻ visa, master,…trên các cổng thanh toán hàng đầu Việt Nam và thế giới như :</p>\r\n");
      out.write("<p >Paypal, Onepay,… Và khai thác các tuyến điểm du lịch mới lạ như Anh, Âu, Úc, Mỹ, Nhật Bản, Hàn Quốc, Dubai, Myanmar…</p>\r\n");
      out.write("<div class=\"a_img\">\r\n");
      out.write("<img src=\"../img/GioiThieu/ban-quyen-thuong-hieu.png\" alt=\"Giấy chứng nhận nhãn hiệu Du Lịch Việt do Cục sở hữu trí tuệ cấp\" width=\"400\" height=\"415\" style=\"margin-left:100px;margin-right:100px\">\r\n");
      out.write("<p>Giấy chứng nhận nhãn hiệu Du Lịch Việt do Cục sở hữu trí tuệ cấp</p>\r\n");
      out.write("<p>Logo Du Lịch Việt đã được đăng ký bản quyền</p>\r\n");
      out.write("<img src=\"../img/GioiThieu/logo-du-lich-viet-800x261.png\" alt=\"Logo Du Lịch Việt\" width=\"600\" height=\"261\" style=\"margin-left:30px;margin-right:50px;\"> </div>\r\n");
      out.write("<h1 style=\"font-size: 22px;color:#0371B1;margin-top:5px;margin-bottom:15px;margin-left:20px;\">II. Giải thưởng:</h1>\r\n");
      out.write("<p>Ngày 26/9/2014, lần thứ 2 liên tiếp, công ty Du Lịch Việt được vinh danh và trao tặng giải thưởng cao quý này. </p>\r\n");
      out.write("<p><strong>Đặc biệt trong năm 2014 công ty đã có bước tiến vượt bậc khi xếp vị trí thứ 3 trong 10 công ty du lịch hàng đầu Việt Nam ở cả hai lĩnh vực nội địa và lĩnh vực đưa khách đi du lịch nước ngoài. </strong></p>\r\n");
      out.write("<div class=\"a_img\">\r\n");
      out.write("<img  src=\"../img/GioiThieu/cup-10.png\" alt=\"TOP 10 công ty du lịch hàng đầu Việt Nam 2014\" width=\"400\" height=\"400\" style=\"margin-left:100px; margin-right:100px;\">\r\n");
      out.write("<p>Top 10 công ty du lịch hàng đầu Việt Nam đưa khách du lịch Quốc tế và Nội địa năm 2013</p>\r\n");
      out.write("</div>\r\n");
      out.write("<p>Ngày 27/3/2014, lần thứ 4 liên tiếp Du Lịch Việt được đón nhận giải thưởng danh giá “TOP 10 DOANH NGHIỆP LỮ HÀNH HÀNG ĐẦU TPHCM” do sở VHTT&amp;DL trao tặng</p>\r\n");
      out.write("<table width=\"100%\" align=\"center\" style=\"margin-left:10px;margin-right:10px\">\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr><td >\r\n");
      out.write("<div class=\"img\"><img title=\"Top 10 doanh nghiệp lữ hành Nội địa hàng đầu\" src=\"../img/GioiThieu/giai-thuong-du-lich-2014.png\" alt=\"giai-thuong-du-lich-2014\" width=\"150\" height=\"245\" >\r\n");
      out.write("</div></td>\r\n");
      out.write("<td >\r\n");
      out.write("<div class=\"img\"><img title=\"Top 10 doanh nghiệp lữ hành Outbound hàng đầu\" src=\"../img/GioiThieu/giai-thuong-outbound-2014.png\" alt=\"giai-thuong-outbound-2014\" width=\"150\" height=\"245\">\r\n");
      out.write("</div></td>\r\n");
      out.write("<td>\r\n");
      out.write("  <div class=\"img\">\r\n");
      out.write("  <img title=\"Top 10 Website TMĐT du lịch hàng đầu\" src=\"../img/GioiThieu/giai-thuong-website-2014.png\" alt=\"giai-thuong-website-2014\" width=\"150\" height=\"245\">\r\n");
      out.write("</div></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<p>Năm 2013, Du Lịch Việt Vinh dự 3 năm liên tiếp đạt những giải thưởng cao quý do sở VHTT-DL Tp.HCM trao tặng:</p>\r\n");
      out.write("<table width=\"100%\" align=\"center\" style=\"margin-left:20px;margin-right:20px\">\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr><td >\r\n");
      out.write("<div class=\"img\"><img class=\"size-full wp-image-44025\" src=\"../img/GioiThieu/top-10-doanh-nghiep-lu-hanh-hang-dau.png\" alt=\"Top 10 doanh nghiệp lữ hành Outbound hàng đầu\" width=\"150\" height=\"254\">\r\n");
      out.write("</div></td>\r\n");
      out.write("<td >\r\n");
      out.write("<div class=\"img\"><img class=\"size-full wp-image-44025\" src=\"../img/GioiThieu/top-10-lu-hanh-noi-dia.png\" alt=\"Top 10 doanh nghiệp lữ hành Outbound hàng đầu\" width=\"150\" height=\"254\">\r\n");
      out.write("</div></td>\r\n");
      out.write("<td>\r\n");
      out.write("  <div class=\"img\">\r\n");
      out.write("  <img class=\"size-full wp-image-44025\" src=\"../img/GioiThieu/top-10-doanh-nghiep-lu-hanh-hang-dau.png\" alt=\"Top 10 doanh nghiệp lữ hành Outbound hàng đầu\" width=\"150\" height=\"254\">\r\n");
      out.write("</div></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<p >Đầu năm 2013, Du Lịch Việt vinh dự đón nhận giải thưởng “DOANH NGHIỆP TRIỂN VỌNG HỘI NHẬP ASEAN”:</p>\r\n");
      out.write("<img class=\"size-full wp-image-42457\" src=\"../img/GioiThieu/doanh-nghiep-trien-vong-hoi-nhap-asean-2013.jpg\" alt=\"Doanh nghiệp triển vọng hội nhập Asean\" width=\"400\" height=\"300\" style=\"margin-left:140px;margin-right:140px\"><p class=\"wp-caption-text\">Doanh nghiệp triển vọng hội nhập Asean</p>\r\n");
      out.write("<p>Đầu năm 2012 Du Lịch Việt vinh dự đón nhận các giải thưởng:</p>\r\n");
      out.write("<table width=\"100%\" align=\"center\" style=\"margin-left:20px;margin-right:20px\">\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr><td >\r\n");
      out.write("<div class=\"img\"><img class=\"size-full wp-image-17404  \" title=\"TOP 10 doanh nghiệp lữ hành Outbound hàng đầu\" src=\"../img/GioiThieu/top-ten-2012.jpg\" alt=\"TOP 10 doanh nghiệp lữ hành Outbound hàng đầu\" width=\"150\" height=\"181\">\r\n");
      out.write("</div></td>\r\n");
      out.write("<td >\r\n");
      out.write("<div class=\"img\"><img title=\"TOP 10 doanh nghiệp lữ hành Nội địa hàng đầu\" src=\"../img/GioiThieu/top-5-website-thuong-mai-dien-tu.jpg\" alt=\"TOP 10 doanh nghiệp lữ hành Nội địa hàng đầu\" width=\"150\" height=\"181\">\r\n");
      out.write("</div></td>\r\n");
      out.write("<td>\r\n");
      out.write("  <div class=\"img\">\r\n");
      out.write("  <img  title=\"TOP 10 website TMĐT du lịch hàng đầu Tp.HCM\" src=\"../img/GioiThieu/cup-trang-web.png\" alt=\"TOP 10 website TMĐT du lịch hàng đầu Tp.HCM\" width=\"150\" height=\"181\">\r\n");
      out.write("</div></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"../Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"../Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <footer class=\"footer-distributed\">\r\n");
      out.write("    <div class=\"footer-left\">\r\n");
      out.write("      <h3>Du Lịch V<span>à Cuộc Sống</span></h3>\r\n");
      out.write("      <p class=\"footer-links\"> <a href=\"home.jsp\">Trang Chủ</a> ·\r\n");
      out.write("       <a href=\"Camnangdulich.jsp\">Cẩm nang</a> · <a href=\"DuLichTrongNuoc.jsp\">Du Lịch Nội Địa</a> \r\n");
      out.write("       · <a href=\"DuLichNuocNgoai.jsp\">Du Lịch Nước Ngoài</a> \r\n");
      out.write("       · <a href=\"#\">Khách Hàng</a> · <a href=\"GioiThieu.jsp\">Giới Thiệu</a></p>\r\n");
      out.write("      <p class=\"footer-company-name\">CÔNG TY DU LỊCH VIỆT 2015</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-center\">\r\n");
      out.write("      <div> <i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("        <p><span> 175, Nguyễn Thái Bình ,</span>Quận 1,Tp.HCM.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("        <p>+1 555 123456</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("        <p><a href=\"mailto:support@company.com\">phongkhachhang@vtc.com</a></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-right\">\r\n");
      out.write("      <p class=\"footer-company-about\"> <span>Công ty Du lịch Việt</span> Tận hưởng chuyến du lịch đầy ý nghĩa.</p>\r\n");
      out.write("      <div class=\"footer-icons\"> <a href=\"#\"><i class=\"fa fa-facebook\"></i></a> <a href=\"#\"><i class=\"fa fa-twitter\"></i></a> <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a> <a href=\"#\"><i class=\"fa fa-github\"></i></a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <!-- InstanceEndEditable --></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- InstanceEnd --></html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
