/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-01-06 16:38:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.NEWPROJECT.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.User;
import Controller.LoadData;
import java.util.ArrayList;
import org.apache.jasper.tagplugins.jstl.core.ForEach;
import DAO.TypeTourDaoImp;
import Model.Tour_Type;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/NEWPROJECT/html/header.jsp", Long.valueOf(1452055796125L));
    _jspx_dependants.put("/NEWPROJECT/html/footer.jsp", Long.valueOf(1451809395344L));
    _jspx_dependants.put("/NEWPROJECT/html/seach.jsp", Long.valueOf(1451809395544L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"><!-- InstanceBegin template=\"/Templates/home.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>Du Lịch Và Cuộc Sống</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"../Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../css/index/body_contenner.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<!-- InstanceBegin template=\"/Templates/home.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"../Bootstrap/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../Bootstrap/glyphicons.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/bootstrap/js/bootstrap.min.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"../css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Start WOWSlider.com HEAD section -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../engine1/style.css\" />\r\n");
      out.write("<link href=\"../SpryAssets/SpryAccordion.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../engine1/jquery.js\"></script>\r\n");
      out.write("<!-- End WOWSlider.com HEAD section -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		ArrayList<Tour_Type> listTypeTour = (ArrayList<Tour_Type>) session.getAttribute("listTypeTour");
	
      out.write("\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<div id=\"login_loout\">\r\n");
      out.write("\t\t\t\t<div id=\"DangKy\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Đăng Ký </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"DangNhap\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"> Đăng Nhập </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"LienHe\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"> Liên Hệ </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"banner\">\r\n");
      out.write("\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../img/logo/flower banner 1 - Copy.jpg\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Nhập tour cần tìm...\" s /> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-default\" type=\"button\">Seach</button>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /input-group -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.col-lg-6 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"header-hot-line\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-phone-square fa-2x \"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: left; padding-right: 2px;\"></i> <span>\r\n");
      out.write("\t\t\t\t\t\t\t(04-3) 511.33.33<em style=\"color: #666 !important;\">-</em>\r\n");
      out.write("\t\t\t\t\t\t\t01999.102.888\r\n");
      out.write("\t\t\t\t\t\t</span> <i id=\"txt\">(Thời gian làm việc: 8:00 - 17:30 các ngày trong\r\n");
      out.write("\t\t\t\t\t\t\ttuần)</i>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div></div>\r\n");
      out.write("\t\t\t<!--end header-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- InstanceBeginEditable name=\"Change\" -->\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"home.jsp\"><i class=\"fa fa-home\"></i>Trang\r\n");
      out.write("\t\t\t\t\t\t\t\tchủ</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"Camnangdulich.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-book\"></i>Cẩm Nan Du Lịch</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Du Lịch Trong Nước<span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"caret\"></span></a> </a> ");

 	for (Tour_Type los : listTypeTour) {
 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> ");
      out.print(los.getNameType() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Menu 1 <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Submenu 1-1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Submenu 1-2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Submenu 1-3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"file:///G|/NEWPROJECT/dangNhap.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-users\"></i>Khách Hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"GioiThieu.jsp\"><i class=\"fa fa-user\"></i>Giới\r\n");
      out.write("\t\t\t\t\t\t\t\tThiệu</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- InstanceEndEditable -->\r\n");
      out.write("\t\t<!-- InstanceBeginEditable name=\"change\" -->\r\n");
      out.write("\t\t<div id=\"slider\">\r\n");
      out.write("\t\t\t<!-- Start WOWSlider.com BODY section -->\r\n");
      out.write("\t\t\t<div id=\"wowslider-container1\">\r\n");
      out.write("\t\t\t\t<div class=\"ws_images\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><img src=\"../data1/images/01.jpg\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"wows1_0\" /></li>\r\n");
      out.write("\t\t\t\t\t\t<li><img src=\"../data1/images/02.jpg\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"wows1_1\" /></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://wowslider.net\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/images/03.jpg\" alt=\"wowslider.net\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"wows1_2\" /></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><img src=\"../data1/images/04.jpg\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"wows1_3\" /></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ws_bullets\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" title=\"\"><span><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/images/01.jpg\" alt=\"\" />1</span></a> <a href=\"#\" title=\"\"><span><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/tooltips/02.jpg\" alt=\"\" />2</span></a> <a href=\"#\" title=\"\"><span><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/tooltips/03.jpg\" alt=\"\" />3</span></a> <a href=\"#\" title=\"\"><span><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../data1/tooltips/04.jpg\" alt=\"\" />4</span></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ws_script\" style=\"position: absolute; left: -99%\">\r\n");
      out.write("\t\t\t\t\t<a href=\"http://wowslider.com\">bootstrap carousel</a> by\r\n");
      out.write("\t\t\t\t\tWOWSlider.com v8.6\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ws_shadow\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"../engine1/wowslider.js\"></script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"../engine1/script.js\"></script>\r\n");
      out.write("\t\t\t<!-- End WOWSlider.com BODY section -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End Content Wrapper. Contains page content -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>CẨM NANG DU LỊCH</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"../Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"../Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../css/UpdateAddmin/stylenewaddmin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"../css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Start WOWSlider.com HEAD section -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../engine1/style.css\" />\r\n");
      out.write("<link href=\"../css/index/body_contenner.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../SpryAssets/SpryAccordion.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../engine1/jquery.js\"></script>\r\n");
      out.write("<script src=\"../SpryAssets/SpryAccordion.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- End WOWSlider.com HEAD section -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write(" <div id=\"right\">\r\n");
      out.write("    <div id=\"video\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-sm-5\">\r\n");
      out.write("            <h3>\r\n");
      out.write("              <p >Du Lịch Việt</p>\r\n");
      out.write("            </h3>\r\n");
      out.write("            <div class=\"embed-responsive embed-responsive-16by9\">\r\n");
      out.write("              <iframe class=\"embed-responsive-item\" src=\"../video/Welcome to vietnam.mp4\"></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p ><strong>Đến với Việt Nam để cảm nhận những vẻ đẹp tiềm ẩn.\r\n");
      out.write("              Cùng với màu sắc văn hóa rực rỡ của 54 dân tộc. </strong></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--start seach-->\r\n");
      out.write("    <div id=\"seach\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        <p style=\"color:#F00;\">Tìm Tour Du Lịch</p>\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\">Khởi Hành Từ</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseOne\" class=\"panel-collapse collapse in\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=1\">\r\n");
      out.write("                  <input type=\"checkbox\" checked=\"checked\" />\r\n");
      out.write("                  Hồ Chí Minh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=3\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Hà Nội</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=4\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Đà Nẵng</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=5\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Cần Thơ</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=6\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Hải Phòng</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=8\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Nha Trang</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=10\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Huế</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=11\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quy Nhơn</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=15\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quảng Ngãi</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=17\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Quảng Ninh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=18\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Buôn Ma Thuột</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=19\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Vinh</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=20\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Cà Mau</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?d=22\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Rạch Giá</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\">Theo Giá</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseTwo\" class=\"panel-collapse collapse\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul >\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=0\">\r\n");
      out.write("                  <input type=\"checkbox\" checked=\"checked\" />\r\n");
      out.write("                  Tất cả</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=25\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Dưới 1 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=26\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  1- 2  Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=27\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  2-4 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=28\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  4-6 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=29\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  6-10 Triệu</a></li>\r\n");
      out.write("                <li> <a href=\"/du-lich-viet-nam.aspx?pr=30\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Trên 10 Triệu</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("          <div class=\"panel-heading\">\r\n");
      out.write("            <h4 class=\"panel-title\"> <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\">Theo Miền</a></h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"collapseThree\" class=\"panel-collapse collapse\">\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-bac.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền bắc</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-trung.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền trung</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-tay.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền tây</a></li>\r\n");
      out.write("                <li><a href=\"/du-lich-viet-nam/tour-mien-dong.aspx\">\r\n");
      out.write("                  <input type=\"checkbox\" />\r\n");
      out.write("                  Tour miền đông</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <h3><a href=\"#\" class=\"btn btn-primary btn-block\" role=\"button\">Tìm Kiếm</a></h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--end seachs-->\r\n");
      out.write("    <!--start Khuyen Mai-->\r\n");
      out.write("    <div id=\"khuyen_mai\">\r\n");
      out.write("      <h3>\r\n");
      out.write("        <p style=\"color:#F00;\">Tour Bán Chạy Nhất</p>\r\n");
      out.write("      </h3>\r\n");
      out.write("      <div id=\"row\">\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("          <div class=\"thumbnail sml\"> <img src=\"../img/TourKhuyenMai/bienNhaTrang.jpg\"  />\r\n");
      out.write("            <h4> <a href=\"#\">Du Lịch Nha Trang </a></h4>\r\n");
      out.write("            <p>Cho thuê thiết bị sân khấu bàn ghế dù che “Mở bán Căn hộ cao cấp Dream Home”</p>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--end Khuyen Mai-->\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <div class=\"tittle\">\r\n");
      out.write("    <a href=\"../html/Camnangdulich.jsp\" ><div class=\"backgr\">Tour Hot</div></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"list\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-sm-8 col-md-6\">\r\n");
      out.write("        <div class=\"thumbnail\"> <img src=\"../infoTour/DuLichTrongNuoc/DaLat/Tour Đà Lạt 3 ngày 2 đêm đường hầm đất sét ĐÀ LẠT - Đường Hầm Đất Sét/pictures/bbi1420613859_tour-du-lich-da-lat-chinh-phuc-dinh-langbiang-3-ngay-2-dem.jpg\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\">Tour Du Lịch Tham Quan Nội Thành Đà Lạt - City Tour Đà Lạt 1 Ngày</a></h3>\r\n");
      out.write("            <p>Xuất phát từ đồi Robin cao 1.517m, vượt qua dãy đồi núi trập trùng, rừng thông vi vút, cáp treo Đà Lạt hiện nay là tuyến cáp treo dài nhất Việt Nam (2.267m) </p>\r\n");
      out.write("            <span class=\"sell-price\"> 3.700.000 <sup>đ</sup></span> <span class=\"original-price\"><del> 5.200.000  <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../html/datTour.jsp\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../html/TourPhanThiet.jsp\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("        <div class=\"thumbnail sml\"> <img src=\"../infoTour/DuLichTrongNuoc/NhaTrang/nhatrang.jpg\"  />\r\n");
      out.write("          <h4> <a href=\"../#\">Du lịch Nha Trang  </a></h4>\r\n");
      out.write("          <p>Miễn phí phụ thu trẻ dưới 6 tuổi ngủ cùng cha mẹ .</p>\r\n");
      out.write("          <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span> <span class=\"original-price\"><del> 3.400.000 <sup>đ</sup></del></span>\r\n");
      out.write("          <div class=\"pull-right\" >\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-sm btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-sm btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("        <div class=\"thumbnail sml\"> <img src=\"../infoTour/DuLichTrongNuoc/HaNoi/HaNoiDongBac/hobabe.jpg\"  />\r\n");
      out.write("          <h4> <a href=\"../#\">Hà Nội - Đông Bắc </a></h4>\r\n");
      out.write("          <p>Xe đưa Quý khách ra bến thuyền, đoàn lên thuyền tham quan Hồ Ba Bể (5 tiếng) </p>\r\n");
      out.write("          <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span> <span class=\"original-price\"><del> 3.400.000 <sup>đ</sup></del></span>\r\n");
      out.write("          <div class=\"pull-right\" >\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-sm btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-sm btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("        <div class=\"thumbnail sml\"> <img src=\"../infoTour/DuLichTrongNuoc/BenTre/BenTre-Mytho/eia1436420446_tour-du-lich-my-tho-ben-tre-can-tho-trong-2-ngay-1-dem.jpg\"  />\r\n");
      out.write("          <h4> <a href=\"../#\">Mỹ Tho - Bến Tre  </a></h4>\r\n");
      out.write("          <p>uý khách xuống đò chèo con rạch nhỏ để chiêm ngưỡng những hàng dừa nước </p>\r\n");
      out.write("          <span class=\"sell-price\"> 2.000.000 <sup>đ</sup></span> <span class=\"original-price\"><del> 3.400.000 <sup>đ</sup></del></span>\r\n");
      out.write("          <div class=\"pull-right\" >\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-sm btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-sm btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"tittle\">\r\n");
      out.write("    <a href=\"../html/Camnangdulich.jsp\"><div class=\"backgr\">Du Lịch trong Nước</div></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"list\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\" style=\"margin-left:15px;\">\r\n");
      out.write("        <div class=\"thumbnail\"> <img src=\"../infoTour/DuLichTrongNuoc/BinhThuan/Bluebaymuine/bienphanthiet.jpg\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\"> Blue Bay Mũi Né Resort </a></h3>\r\n");
      out.write("            <span class=\"sell-price\">1,690,000 <sup>đ</sup></span> <span class=\"original-price\"><del> 2,100,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\" >\r\n");
      out.write("        <div class=\"thumbnail\"> <img src=\"../infoTour/DuLichTrongNuoc/vungtau/langrungresort/174409-lan-rung-resort-2n1d-tang-lau-hai-san-xong-hoi.jpg\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\"> [Vũng Tàu] Lan Rừng Resort</a></h3>\r\n");
      out.write("            <span class=\"sell-price\"> 1,485,000 <sup>đ</sup></span> <span class=\"original-price\"><del>  2,296,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("        <div class=\"thumbnail\"> <img src=\"../infoTour/DuLichTrongNuoc/BacLieu/NhaThoChaDiep/noi-an-nghi-cua-cha-diep.jpg\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\"> [Bạc Liêu] Viếng Nhà Thờ Cha Diệp </a></h3>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span> <span class=\"original-price\"><del> 3.400.000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\" style=\"margin-left:15px;\">\r\n");
      out.write("        <div class=\"thumbnail img-responsive \"><img  height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\" src=\"../infoTour/DuLichTrongNuoc/BinhThuan/BinhChauLaGi/lagi.jpg\" alt=\"\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\"> Tour Bình Châu – Lagi  </a></h3>\r\n");
      out.write("            <span class=\"sell-price\">879,000 <sup>đ</sup></span> <span class=\"original-price\"><del>  1,590,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("        <div class=\"thumbnail img-responsive \"><img  height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\" src=\"../infoTour/DuLichTrongNuoc/NhaTrangPhuYenQuyNhon/nhatrangphuyenquynhon.jpg\" alt=\"\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\">Quy Nhơn–Phú Yên–Nha Trang </a></h3>\r\n");
      out.write("            <span class=\"sell-price\">2,390,000 <sup>đ</sup></span> <span class=\"original-price\"><del> 4,390,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("        <div class=\"thumbnail img-responsive \"><img  height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\" src=\"../infoTour/DuLichTrongNuoc/DaLat/thacPongour/thacpongour.jpg\" alt=\"\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\">Thác Pongour – Thác Voi </a></h3>\r\n");
      out.write("            <span class=\"sell-price\"> 330,000 <sup>đ</sup></span> <span class=\"original-price\"><del> 660,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"tittle\">\r\n");
      out.write("<a href=\"../html/Camnangdulich.jsp\"> <div class=\"backgr\">Du Lịch Nước Ngoài</div></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"list\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\" style=\"margin-left:15px;\">\r\n");
      out.write("        <div class=\"thumbnail\"> <img src=\"../infoTour/DuLichNuocNgoai/campuchia/campuchia.jpg\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\">Campuchia - Tour Cao Nguyên Bokor </a></h3>\r\n");
      out.write("            <span class=\"sell-price\">3,279,000 <sup>đ</sup></span> <span class=\"original-price\"><del>  5,179,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\" >\r\n");
      out.write("        <div class=\"thumbnail\"> <img src=\"../infoTour/DuLichNuocNgoai/campuchia/Tour Siemriep - Phnompenh/208647-black-friday-cambodia-siemriep-phnompenh-4n3d-danh-cho-01-nguoi.jpg\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\"> Tour Siemriep - Phnompenh </a></h3>\r\n");
      out.write("            <span class=\"sell-price\"> 3,500,000 <sup>đ</sup></span> <span class=\"original-price\"><del> 3,900,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("        <div class=\"thumbnail\"> <img src=\"../infoTour/DuLichNuocNgoai/thailan/bangkok-pataya/208639-black-friday-thailand-tour-bangkok-pataya-5n4d-danh-cho-01-nguoi.jpg\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\"> Tour Bangkok - Pataya</a></h3>\r\n");
      out.write("            <span class=\"sell-price\"> 5,500,000 <sup>đ</sup></span> <span class=\"original-price\"><del> 5,890,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\" style=\"margin-left:15px;\">\r\n");
      out.write("        <div class=\"thumbnail img-responsive \"><img  height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\" src=\"../infoTour/DuLichNuocNgoai/campuchia/thienduongbiendao/97485_body (3).jpg\" alt=\"\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\">  Campuchia Thiên Đường Biển Đảo </a></h3>\r\n");
      out.write("            <span class=\"sell-price\"> 3,400,000 <sup>đ</sup></span> <span class=\"original-price\"><del>  4,900,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("        <div class=\"thumbnail img-responsive \"><img  height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\" src=\"../infoTour/DuLichNuocNgoai/campuchia/sỉmiephuyenbi/168398-tour-kham-pha-siem-riep-huyen-bi-phnompenh-cao-nguyen-bokor-sihanoukville-dao-thien-duong-kohrong-ks-3-5-6n5d-danh-cho-1-khach.jpg\" alt=\"\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\"> Siêm Riệp – Phnompenh </a></h3>\r\n");
      out.write("            <span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span> <span class=\"original-price\"><del> 3.400.000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("        <div class=\"thumbnail img-responsive \"><img  height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\" src=\"../infoTour/DuLichNuocNgoai/campuchia/giaimasiemriep/193078-campuchia-4n3d-giai-ma-siemriep-huyen-bi-phnompenh-danh-cho-1-nguoi.jpg\" alt=\"\" />\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("            <h3> <a href=\"../#\"> Tour Giải Mã Siemriep Huyền Bí</a></h3>\r\n");
      out.write("            <span class=\"sell-price\"> 2,990,000 <sup>đ</sup></span> <span class=\"original-price\"><del> 4,800,000 <sup>đ</sup></del></span>\r\n");
      out.write("            <p><a href=\"../#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a href=\"../#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- InstanceEndEditable -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"../Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"../Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <footer class=\"footer-distributed\">\r\n");
      out.write("    <div class=\"footer-left\">\r\n");
      out.write("      <h3>Du Lịch V<span>à Cuộc Sống</span></h3>\r\n");
      out.write("      <p class=\"footer-links\"> <a href=\"home.jsp\">Trang Chủ</a> ·\r\n");
      out.write("       <a href=\"Camnangdulich.jsp\">Cẩm nang</a> · <a href=\"DuLichTrongNuoc.jsp\">Du Lịch Nội Địa</a> \r\n");
      out.write("       · <a href=\"DuLichNuocNgoai.jsp\">Du Lịch Nước Ngoài</a> \r\n");
      out.write("       · <a href=\"#\">Khách Hàng</a> · <a href=\"GioiThieu.jsp\">Giới Thiệu</a></p>\r\n");
      out.write("      <p class=\"footer-company-name\">CÔNG TY DU LỊCH VIỆT 2015</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-center\">\r\n");
      out.write("      <div> <i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("        <p><span> 175, Nguyễn Thái Bình ,</span>Quận 1,Tp.HCM.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("        <p>+1 555 123456</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("        <p><a href=\"mailto:support@company.com\">phongkhachhang@vtc.com</a></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-right\">\r\n");
      out.write("      <p class=\"footer-company-about\"> <span>Công ty Du lịch Việt</span> Tận hưởng chuyến du lịch đầy ý nghĩa.</p>\r\n");
      out.write("      <div class=\"footer-icons\"> <a href=\"#\"><i class=\"fa fa-facebook\"></i></a> <a href=\"#\"><i class=\"fa fa-twitter\"></i></a> <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a> <a href=\"#\"><i class=\"fa fa-github\"></i></a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- InstanceEnd --></html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
