/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-01-11 03:27:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.NEWPROJECT.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.Tour;
import java.util.ArrayList;
import Model.User;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/NEWPROJECT/html/footer.jsp", Long.valueOf(1452329166634L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<!-- InstanceBegin template=\"/Templates/home.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>Du Lịch Và Cuộc Sống</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/css.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/glyphicons.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/css/index/body_contenner.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/js/bootstrap.min.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/app.min.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#header').load(\"LoadDataHeader\");\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		ArrayList<Tour> listTour = (ArrayList<Tour>) session.getAttribute("allTour");
	
      out.write("\r\n");
      out.write("\t<div id=\"header\"></div>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "seach.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"tittle\">\r\n");
      out.write("\t\t\t<a href=\"#\"><div class=\"backgr\">Tour Hot</div></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"list\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-8 col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/DaLat/Tour Đà Lạt 3 ngày 2 đêm đường hầm đất sét ĐÀ LẠT - Đường Hầm Đất Sét/pictures/bbi1420613859_tour-du-lich-da-lat-chinh-phuc-dinh-langbiang-3-ngay-2-dem.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">");
      out.print(listTour.get(0).getNameTour());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>");
      out.print(listTour.get(0).getShortContent());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\"> ");
      out.print(listTour.get(0).getNewPrice());
      out.write(" <sup>đ</sup></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t5.200.000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/NEWPROJECT/NEWPROJECT/html/datTour.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"/NEWPROJECT/NEWPROJECT/html/TourPhanThiet.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail sml\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/NhaTrang/nhatrang.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Du lịch Nha Trang </a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>Miễn phí phụ thu trẻ dưới 6 tuổi ngủ cùng cha mẹ .</p>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t3.400.000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-sm btn-primary\" role=\"button\">Đặt\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmua</a> <a href=\"#\" class=\"btn btn-sm btn-default\" role=\"button\">Xem\r\n");
      out.write("\t\t\t\t\t\t\t\t\tThêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail sml\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/HaNoi/HaNoiDongBac/hobabe.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Hà Nội - Đông Bắc </a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>Xe đưa Quý khách ra bến thuyền, đoàn lên thuyền tham quan\r\n");
      out.write("\t\t\t\t\t\t\tHồ Ba Bể (5 tiếng)</p>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t3.400.000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-sm btn-primary\" role=\"button\">Đặt\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmua</a> <a href=\"#\" class=\"btn btn-sm btn-default\" role=\"button\">Xem\r\n");
      out.write("\t\t\t\t\t\t\t\t\tThêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-md-6 small\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail sml\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/BenTre/BenTre-Mytho/eia1436420446_tour-du-lich-my-tho-ben-tre-can-tho-trong-2-ngay-1-dem.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Mỹ Tho - Bến Tre </a>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>uý khách xuống đò chèo con rạch nhỏ để chiêm ngưỡng những\r\n");
      out.write("\t\t\t\t\t\t\thàng dừa nước</p>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sell-price\"> 2.000.000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t3.400.000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-sm btn-primary\" role=\"button\">Đặt\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmua</a> <a href=\"#\" class=\"btn btn-sm btn-default\" role=\"button\">Xem\r\n");
      out.write("\t\t\t\t\t\t\t\t\tThêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"tittle\">\r\n");
      out.write("\t\t\t<a href=\"/NEWPROJECT/NEWPROJECT/html/Camnangdulich.jsp\"><div\r\n");
      out.write("\t\t\t\t\tclass=\"backgr\">Du Lịch trong Nước</div></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"list\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\" style=\"margin-left: 15px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/BinhThuan/Bluebaymuine/bienphanthiet.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> Blue Bay Mũi Né Resort </a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\">1,690,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2,100,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/vungtau/langrungresort/174409-lan-rung-resort-2n1d-tang-lau-hai-san-xong-hoi.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> [Vũng Tàu] Lan Rừng Resort</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\"> 1,485,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2,296,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/BacLieu/NhaThoChaDiep/noi-an-nghi-cua-cha-diep.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> [Bạc Liêu] Viếng Nhà Thờ Cha Diệp </a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t3.400.000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\" style=\"margin-left: 15px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail img-responsive \">\r\n");
      out.write("\t\t\t\t\t\t<img height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/BinhThuan/BinhChauLaGi/lagi.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> Tour Bình Châu – Lagi </a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\">879,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t1,590,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail img-responsive \">\r\n");
      out.write("\t\t\t\t\t\t<img height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/NhaTrangPhuYenQuyNhon/nhatrangphuyenquynhon.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Quy Nhơn–Phú Yên–Nha Trang </a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\">2,390,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t4,390,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail img-responsive \">\r\n");
      out.write("\t\t\t\t\t\t<img height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichTrongNuoc/DaLat/thacPongour/thacpongour.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Thác Pongour – Thác Voi </a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\"> 330,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t660,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"tittle\">\r\n");
      out.write("\t\t\t<a href=\"/NEWPROJECT/NEWPROJECT/html/Camnangdulich.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"backgr\">Du Lịch Nước Ngoài</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"list\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\" style=\"margin-left: 15px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichNuocNgoai/campuchia/campuchia.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Campuchia - Tour Cao Nguyên Bokor </a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\">3,279,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t5,179,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichNuocNgoai/campuchia/Tour Siemriep - Phnompenh/208647-black-friday-cambodia-siemriep-phnompenh-4n3d-danh-cho-01-nguoi.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> Tour Siemriep - Phnompenh </a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\"> 3,500,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t3,900,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichNuocNgoai/thailan/bangkok-pataya/208639-black-friday-thailand-tour-bangkok-pataya-5n4d-danh-cho-01-nguoi.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> Tour Bangkok - Pataya</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\"> 5,500,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t5,890,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\" style=\"margin-left: 15px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail img-responsive \">\r\n");
      out.write("\t\t\t\t\t\t<img height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichNuocNgoai/campuchia/thienduongbiendao/97485_body (3).jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> Campuchia Thiên Đường Biển Đảo </a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\"> 3,400,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t4,900,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail img-responsive \">\r\n");
      out.write("\t\t\t\t\t\t<img height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichNuocNgoai/campuchia/sỉmiephuyenbi/168398-tour-kham-pha-siem-riep-huyen-bi-phnompenh-cao-nguyen-bokor-sihanoukville-dao-thien-duong-kohrong-ks-3-5-6n5d-danh-cho-1-khach.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> Siêm Riệp – Phnompenh </a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\"> 1.330.000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t3.400.000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"thumbnail img-responsive \">\r\n");
      out.write("\t\t\t\t\t\t<img height=\"300\" itemprop=\"image\" style=\"max-width: 100%;\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"F:/GOC_HOC_TAP/2015-2016/LTW/infoTour/DuLichNuocNgoai/campuchia/giaimasiemriep/193078-campuchia-4n3d-giai-ma-siemriep-huyen-bi-phnompenh-danh-cho-1-nguoi.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> Tour Giải Mã Siemriep Huyền Bí</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sell-price\"> 2,990,000 <sup>đ</sup></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"original-price\"><del>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t4,800,000 <sup>đ</sup>\r\n");
      out.write("\t\t\t\t\t\t\t\t</del></span>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Đặt mua</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Xem Thêm</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- InstanceEndEditable -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- InstanceEndEditable -->\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/NEWPROJECT/NEWPROJECT/css/footer-distributed-with-address-and-phones.css\">\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"/NEWPROJECT/NEWPROJECT/Bootstrap/glyphicons.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/NEWPROJECT/NEWPROJECT/Bootstrap/dist/js/app.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <footer class=\"footer-distributed\">\r\n");
      out.write("    <div class=\"footer-left\">\r\n");
      out.write("      <h3>Du Lịch V<span>à Cuộc Sống</span></h3>\r\n");
      out.write("      <p class=\"footer-links\"> <a href=\"home.jsp\">Trang Chủ</a> ·\r\n");
      out.write("       <a href=\"Camnangdulich.jsp\">Cẩm nang</a> · <a href=\"DuLichTrongNuoc.jsp\">Du Lịch Nội Địa</a> \r\n");
      out.write("       · <a href=\"DuLichNuocNgoai.jsp\">Du Lịch Nước Ngoài</a> \r\n");
      out.write("       · <a href=\"#\">Khách Hàng</a> · <a href=\"GioiThieu.jsp\">Giới Thiệu</a></p>\r\n");
      out.write("      <p class=\"footer-company-name\">CÔNG TY DU LỊCH VIỆT 2015</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-center\">\r\n");
      out.write("      <div> <i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("        <p><span> 175, Nguyễn Thái Bình ,</span>Quận 1,Tp.HCM.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("        <p>+1 555 123456</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div> <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("        <p><a href=\"mailto:support@company.com\">phongkhachhang@vtc.com</a></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-right\">\r\n");
      out.write("      <p class=\"footer-company-about\"> <span>Công ty Du lịch Việt</span> Tận hưởng chuyến du lịch đầy ý nghĩa.</p>\r\n");
      out.write("      <div class=\"footer-icons\"> <a href=\"#\"><i class=\"fa fa-facebook\"></i></a> <a href=\"#\"><i class=\"fa fa-twitter\"></i></a> <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a> <a href=\"#\"><i class=\"fa fa-github\"></i></a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- InstanceEnd -->\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
