/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-01-03 15:04:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.NEWPROJECT;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dangky_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8]> <html lang=\"en\" class=\"ie8\"> <![endif]-->\r\n");
      out.write("<!--[if IE 9]> <html lang=\"en\" class=\"ie9\"> <![endif]-->\r\n");
      out.write("<!--[if !IE]><!--> <html lang=\"en\"> <!--<![endif]-->\r\n");
      out.write("<!-- BEGIN HEAD -->\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<title>Login Form</title>\r\n");
      out.write("\t<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\" />\r\n");
      out.write("\t<meta content=\"\" name=\"description\" />\r\n");
      out.write("\t<meta content=\"\" name=\"author\" />\r\n");
      out.write("\t<!-- BEGIN GLOBAL MANDATORY STYLES -->\r\n");
      out.write("\t<link href=\"assets/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/plugins/bootstrap/css/bootstrap-responsive.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/css/style-metro.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/css/style-responsive.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/css/themes/default.css\" rel=\"stylesheet\" type=\"text/css\" id=\"style_color\"/>\r\n");
      out.write("\t<link href=\"assets/plugins/uniform/css/uniform.default.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/plugins/select2/select2_metro.css\" />\r\n");
      out.write("\t<!-- END GLOBAL MANDATORY STYLES -->\r\n");
      out.write("\t<!-- BEGIN PAGE LEVEL STYLES -->\r\n");
      out.write("\t<link href=\"assets/css/pages/login-soft.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<!-- END PAGE LEVEL STYLES -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("</head>\r\n");
      out.write("<!-- END HEAD -->\r\n");
      out.write("<!-- BEGIN BODY -->\r\n");
      out.write("<body class=\"login\">\r\n");
      out.write("\t<!-- BEGIN LOGO -->\r\n");
      out.write("\t<div class=\"logo\">\r\n");
      out.write("\t\t<!-- PUT YOUR LOGO HERE -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END LOGO -->\r\n");
      out.write("\t<!-- BEGIN LOGIN -->\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- BEGIN REGISTRATION FORM -->\r\n");
      out.write("\t\t<form class=\"form-vertical login-form\" action=\"../DangKy\" method=\"post\">\r\n");
      out.write("\t\t\t<h3 >Tạo Tài khoản</h3>\r\n");
      out.write("\t\t\t<p>Điền Thông Tin vào From sau</p>\r\n");
      out.write("\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">Họ Và Tên</label>\r\n");
      out.write("\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-icon left\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-font\"></i>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"m-wrap placeholder-no-fix\" type=\"text\" placeholder=\"Họ Và Tên\" name=\"fullname\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->\r\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">Email</label>\r\n");
      out.write("\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-icon left\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"m-wrap placeholder-no-fix\" type=\"text\" placeholder=\"Email\" name=\"email\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">Địa Chỉ</label>\r\n");
      out.write("\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-icon left\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-ok\"></i>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"m-wrap placeholder-no-fix\" type=\"text\" placeholder=\"Địa Chỉ\" name=\"address\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">Số điện thoại</label>\r\n");
      out.write("\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-icon left\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-location-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"m-wrap placeholder-no-fix\" type=\"text\" placeholder=\"Số điện thoại\" name=\"phone\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p>Điền Thông Tin Tài Khoản Của Bạn Vào From Sau :</p>\r\n");
      out.write("\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">Tên Đăng Nhập</label>\r\n");
      out.write("\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-icon left\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"m-wrap placeholder-no-fix\" type=\"text\" autocomplete=\"off\" placeholder=\"Tên Đăng Nhập\" name=\"username\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">Mật Khẩu</label>\r\n");
      out.write("\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-icon left\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-lock\"></i>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"m-wrap placeholder-no-fix\" type=\"password\" autocomplete=\"off\" id=\"register_password\" placeholder=\"Mật Khẩu\" name=\"password\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">Nhập Lại Mật Khẩu</label>\r\n");
      out.write("\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-icon left\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-ok\"></i>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"m-wrap placeholder-no-fix\" type=\"password\" autocomplete=\"off\" placeholder=\"Nhập Lại Mật Khẩu\" name=\"rpassword\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t<label class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"tnc\"/> Tôi Đồng ý <a href=\"#\">tả các điều khoản </a>\r\n");
      out.write("\t\t\t\t\t</label>  \r\n");
      out.write("\t\t\t\t\t<div id=\"register_tnc_error\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-actions\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"register-submit-btn\" class=\"btn green pull-right\">\r\n");
      out.write("\t\t\t\tĐăng Nhập <i class=\"m-icon-swapright m-icon-white\"></i>\r\n");
      out.write("\t\t\t\t</button>            \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!-- END REGISTRATION FORM -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END LOGIN -->\r\n");
      out.write("\t<!-- BEGIN COPYRIGHT -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- END COPYRIGHT -->\r\n");
      out.write("\t<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->\r\n");
      out.write("\t<!-- BEGIN CORE PLUGINS -->   <script src=\"assets/plugins/jquery-1.10.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/jquery-migrate-1.2.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->\r\n");
      out.write("\t<script src=\"assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js\" type=\"text/javascript\"></script>      \r\n");
      out.write("\t<script src=\"assets/plugins/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"assets/plugins/excanvas.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/respond.min.js\"></script>  \r\n");
      out.write("\t<![endif]-->   \r\n");
      out.write("\t<script src=\"assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/jquery.blockui.min.js\" type=\"text/javascript\"></script>  \r\n");
      out.write("\t<script src=\"assets/plugins/jquery.cookie.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/uniform/jquery.uniform.min.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("\t<!-- END CORE PLUGINS -->\r\n");
      out.write("\t<!-- BEGIN PAGE LEVEL PLUGINS -->\r\n");
      out.write("\t<script src=\"assets/plugins/jquery-validation/dist/jquery.validate.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/backstretch/jquery.backstretch.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"assets/plugins/select2/select2.min.js\"></script>\r\n");
      out.write("\t<!-- END PAGE LEVEL PLUGINS -->\r\n");
      out.write("\t<!-- BEGIN PAGE LEVEL SCRIPTS -->\r\n");
      out.write("\t<script src=\"assets/scripts/app.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/scripts/login-soft.js\" type=\"text/javascript\"></script>      \r\n");
      out.write("\t<!-- END PAGE LEVEL SCRIPTS --> \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tjQuery(document).ready(function() {     \r\n");
      out.write("\t\t  App.init();\r\n");
      out.write("\t\t  Login.init();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- END JAVASCRIPTS -->\r\n");
      out.write("\t\r\n");
      out.write("<!-- END BODY -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
